### ISSUE TITLE
ModuleNotFoundError: No module named 'encoder'

### ISSUE THREAD

**Issue by runrunnow** [TencentYoutuResearch/Adv-Makeup#2]
Hi! After we run `python train.py`, an error occurred:
```
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from model import *
  File "/foo/Adv-Makeup/model.py", line 14, in <module>
    from encoder import *
ModuleNotFoundError: No module named 'encoder'
```
 
Could the original authors fix the bug?
Thanks a lot.

**Comment by runrunnow** [comment]
Thanks.The bug has been fixed!
